### PR TITLE
Paper revisions

### PR DESCRIPTION
**Pull request by rkansal47**
Addresses suggestions by @matthewfeickert and @jpata in #43 and #53.

TODO: 
- [x] How do we cite Zenodo ~~and Energyflow~~?

### CODE REVIEW

**Comment by jmduarte** [comment]
https://energyflow.network/faqs/#how-do-i-cite-the-energyflow-package

**Comment by matthewfeickert** [comment]
Hm. My appologies @rkansal47, as when I suggested this in Issue #53 I had it in my memory that Zenodo had a clear citation for it, yet I can also not find it now. :?

I don't want to delay publication because of this ask, so @lnielsen can you please recommend a citation for Zenodo that is desirable for you (and then could we add a CITATION.cff to https://github.com/zenodo/zenodo with it)?

**Comment by matthewfeickert** [comment]
Ah @rkansal47 I've found it on https://about.zenodo.org

> [To cite Zenodo, you can use the following BibTeX](https://github.com/zenodo/zenodo-docs-user/blob/15a726b66531feda8b09e4330f1dca7c9b271a25/content/about/contents.lr?plain=1#L179-L190)
```
@misc{https://doi.org/10.25495/7gxk-rd71,
  doi = {10.25495/7GXK-RD71},
  url = {https://www.zenodo.org/},
  author = {{European Organization For Nuclear Research} and {OpenAIRE}},
  keywords = {FOS: Physical sciences, Publication, Dataset},
  language = {en},
  title = {Zenodo},
  publisher = {CERN},
  year = {2013}
}
```

**Comment by rkansal47** [comment]
Thanks @matthewfeickert! I have added this citation.

**Review by jmduarte — APPROVED** [review]
Looks good!

**Pull request merged**
